--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FAIRYTALE
--------------------------------------------------------

  CREATE TABLE "FB"."FAIRYTALE" 
   (	"STORYNUM" NUMBER, 
	"STORYTITLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FB"."FAIRYTALE"."STORYNUM" IS '동화책 고유번호
';
   COMMENT ON COLUMN "FB"."FAIRYTALE"."STORYTITLE" IS '동화책 제목';
REM INSERTING into FB.FAIRYTALE
SET DEFINE OFF;
Insert into FB.FAIRYTALE (STORYNUM,STORYTITLE) values (0,'노랑이의 모험');
Insert into FB.FAIRYTALE (STORYNUM,STORYTITLE) values (1,'헨젤과그레텔');
Insert into FB.FAIRYTALE (STORYNUM,STORYTITLE) values (99,'테스트용동화입니다.');
Insert into FB.FAIRYTALE (STORYNUM,STORYTITLE) values (2,'백설공주');
Insert into FB.FAIRYTALE (STORYNUM,STORYTITLE) values (3,'빨간모자');
--------------------------------------------------------
--  DDL for Index SYS_C007217
--------------------------------------------------------

  CREATE UNIQUE INDEX "FB"."SYS_C007217" ON "FB"."FAIRYTALE" ("STORYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FAIRYTALE
--------------------------------------------------------

  ALTER TABLE "FB"."FAIRYTALE" ADD PRIMARY KEY ("STORYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FB"."FAIRYTALE" MODIFY ("STORYTITLE" NOT NULL ENABLE);
  ALTER TABLE "FB"."FAIRYTALE" MODIFY ("STORYNUM" NOT NULL ENABLE);
