--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PREPLY
--------------------------------------------------------

  CREATE TABLE "FB"."PREPLY" 
   (	"REPLYNUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"BOARDNUM" NUMBER, 
	"TEXT" VARCHAR2(500 BYTE), 
	"INPUTDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FB"."PREPLY"."REPLYNUM" IS '댓글 고유 번호';
   COMMENT ON COLUMN "FB"."PREPLY"."ID" IS '회원 아이디';
   COMMENT ON COLUMN "FB"."PREPLY"."BOARDNUM" IS '게시판 글 고유 번호';
   COMMENT ON COLUMN "FB"."PREPLY"."TEXT" IS '댓글 내용';
   COMMENT ON COLUMN "FB"."PREPLY"."INPUTDATE" IS '댓글 작성 시간';
REM INSERTING into FB.PREPLY
SET DEFINE OFF;
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (9,'ryan',137,'입력????',to_date('17/03/29 12:19:24','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (3,'ryan',137,'rrrrㄹㄹ',to_date('17/03/29 10:23:30','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (5,'ryan',137,'ㅇㅇㅇ',to_date('17/03/29 10:55:14','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (6,'ryan',137,'ㄱㄴㄷㄹ',to_date('17/03/29 10:55:20','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (7,'ryan',137,'수정수정 ㅠㅠㅠㅠㅠ',to_date('17/03/29 10:56:55','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (8,'ryan',137,'ㅠㅠㅠㅠㅠㅠㅠㅠ',to_date('17/03/29 11:34:31','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (13,'aaa',137,'asdfasdf',to_date('17/03/29 12:28:49','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (11,'ryan',137,'ㅡㅡㅡ',to_date('17/03/29 12:25:03','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (12,'ryan',137,'&lt;input type="text"&gt;',to_date('17/03/29 12:28:08','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (14,'aaa',137,'asdfasdf',to_date('17/03/29 12:28:53','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (21,'ryan',141,'dsds',to_date('17/03/30 09:20:35','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (41,'ryan',130,'ddd',to_date('17/04/12 10:00:20','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (61,'eunji',161,'dfs',to_date('17/04/26 20:19:23','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (81,'test',161,'ㅁㄴㅇ',to_date('17/04/27 08:50:09','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (101,'eunji',181,'힘들어요',to_date('17/05/01 14:45:58','RR/MM/DD HH24:MI:SS'));
Insert into FB.PREPLY (REPLYNUM,ID,BOARDNUM,TEXT,INPUTDATE) values (102,'eunji',135,'좋겠지?',to_date('17/05/01 14:46:11','RR/MM/DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Index SYS_C007233
--------------------------------------------------------

  CREATE UNIQUE INDEX "FB"."SYS_C007233" ON "FB"."PREPLY" ("REPLYNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PREPLY
--------------------------------------------------------

  ALTER TABLE "FB"."PREPLY" ADD PRIMARY KEY ("REPLYNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FB"."PREPLY" MODIFY ("TEXT" NOT NULL ENABLE);
  ALTER TABLE "FB"."PREPLY" MODIFY ("BOARDNUM" NOT NULL ENABLE);
  ALTER TABLE "FB"."PREPLY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FB"."PREPLY" MODIFY ("REPLYNUM" NOT NULL ENABLE);
