--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCENE
--------------------------------------------------------

  CREATE TABLE "FB"."SCENE" 
   (	"SCENENUM" NUMBER, 
	"STORYNUM" NUMBER, 
	"QUIZNUM" NUMBER, 
	"NEXTSCENE1" NUMBER, 
	"NEXTSCENE2" NUMBER, 
	"NEXTSCENE3" NUMBER, 
	"NEXTSCENE4" NUMBER, 
	"FBEXPLAIN" VARCHAR2(500 BYTE), 
	"STORYTEXT1" VARCHAR2(1000 BYTE), 
	"STORYTEXT2" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FB"."SCENE"."SCENENUM" IS '동화책 장면 고유 번호';
   COMMENT ON COLUMN "FB"."SCENE"."STORYNUM" IS '동화책 고유번호
';
   COMMENT ON COLUMN "FB"."SCENE"."QUIZNUM" IS '퀴즈 고유번호';
   COMMENT ON COLUMN "FB"."SCENE"."NEXTSCENE1" IS '선택1을 했을시 다음 장면';
   COMMENT ON COLUMN "FB"."SCENE"."NEXTSCENE2" IS '선택2을 했을시 다음 장면';
   COMMENT ON COLUMN "FB"."SCENE"."NEXTSCENE3" IS '선택3을 했을시 다음 장면';
   COMMENT ON COLUMN "FB"."SCENE"."NEXTSCENE4" IS '선택4을 했을시 다음 장면';
   COMMENT ON COLUMN "FB"."SCENE"."FBEXPLAIN" IS '아바타 설명';
   COMMENT ON COLUMN "FB"."SCENE"."STORYTEXT1" IS '스토리 텍스트 1';
   COMMENT ON COLUMN "FB"."SCENE"."STORYTEXT2" IS '스토리텍스트2';
REM INSERTING into FB.SCENE
SET DEFINE OFF;
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (0,1,-1,1,1,1,1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (1,1,23,4,4,4,4,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (47,1,-1,35,35,35,35,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (48,1,-1,-1,-1,-1,-1,null,'Ending#1','별이 된 오누이');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (49,1,13,27,27,27,27,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (50,2,-1,51,51,51,51,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (51,2,-1,52,52,52,52,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (52,2,-1,53,53,53,53,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (53,2,-1,54,54,54,54,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (54,2,-1,55,55,55,55,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (55,2,-1,56,56,56,56,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (56,2,-1,57,57,57,57,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (57,2,-1,58,58,58,58,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (58,2,-1,59,59,59,59,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (59,2,-1,60,60,60,60,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (60,2,-1,61,61,61,61,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (61,2,-1,62,62,62,62,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (62,2,-1,63,63,63,63,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (63,2,-1,64,64,64,64,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (64,2,-1,65,65,65,65,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (65,2,-1,66,66,66,66,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (66,2,-1,67,67,67,67,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (67,2,-1,68,68,68,68,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (68,2,-1,69,69,69,69,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (69,2,-1,70,70,70,70,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (70,2,-1,71,71,71,71,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (71,2,-1,72,72,72,72,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (72,2,-1,73,73,73,73,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (73,2,-1,74,74,74,74,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (74,2,-1,75,75,75,75,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (75,2,-1,-1,-1,-1,-1,null,'Ending#1','행복한 백설공주');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (2,1,-1,3,3,3,3,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (3,1,-1,4,4,4,4,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (4,1,1,5,5,5,-1,'../resources/img/avatarExplain/avatarExplain04.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (5,1,-1,6,6,6,6,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (6,1,2,8,8,7,7,'../resources/img/avatarExplain/avatarExplain06.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (7,1,-1,44,44,44,44,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (8,1,-1,9,9,9,9,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (9,1,-1,11,11,11,11,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (10,1,3,45,45,45,45,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (11,1,4,12,12,12,12,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (12,1,-1,13,13,13,13,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (13,1,5,14,14,14,14,'../resources/img/avatarExplain/avatarExplain13.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (14,1,6,15,15,15,15,'../resources/img/avatarExplain/avatarExplain14.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (15,1,-1,45,45,45,45,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (16,1,7,21,17,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (17,1,8,43,18,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (18,1,-1,19,19,19,19,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (19,1,9,20,20,20,20,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (20,1,-1,48,48,48,48,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (21,1,10,26,22,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (22,1,11,23,23,23,23,'../resources/img/avatarExplain/avatarExplain22.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (23,1,12,25,24,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (24,1,-1,-1,-1,-1,-1,null,'Ending#2','남매의 귀환');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (25,1,-1,-1,-1,-1,-1,null,'Ending#3','제과업계의 큰 손');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (26,1,13,27,27,27,27,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (27,1,14,30,30,28,31,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (28,1,-1,29,29,29,29,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (29,1,-1,-1,-1,-1,-1,null,'Ending#4','그리고 아무도 없었다');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (30,1,15,23,23,23,23,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (31,1,-1,32,32,32,32,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (32,1,16,33,33,33,33,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (33,1,17,36,34,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (34,1,18,29,29,47,29,'../resources/img/avatarExplain/avatarExplain34.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (35,1,-1,-1,-1,-1,-1,null,'Ending#5','힘세고 강한 아빠');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (36,1,19,37,37,37,37,'../resources/img/avatarExplain/avatarExplain36.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (37,1,-1,38,38,38,38,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (38,1,-1,39,39,39,39,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (39,1,20,41,40,-1,-1,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (40,1,-1,-1,-1,-1,-1,null,'Ending#6','이 집은 이제 우리껍니다');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (41,1,-1,35,35,35,35,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (42,1,-1,-1,-1,-1,-1,null,'Ending#2','남매의 귀환');
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (43,1,-1,31,31,31,31,'../resources/img/avatarExplain/avatarExplain43.png',null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (44,1,21,45,45,45,45,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (45,1,22,46,46,46,46,null,null,null);
Insert into FB.SCENE (SCENENUM,STORYNUM,QUIZNUM,NEXTSCENE1,NEXTSCENE2,NEXTSCENE3,NEXTSCENE4,FBEXPLAIN,STORYTEXT1,STORYTEXT2) values (46,1,-1,16,16,16,16,null,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007239
--------------------------------------------------------

  CREATE UNIQUE INDEX "FB"."SYS_C007239" ON "FB"."SCENE" ("SCENENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SCENE
--------------------------------------------------------

  ALTER TABLE "FB"."SCENE" ADD PRIMARY KEY ("SCENENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FB"."SCENE" MODIFY ("QUIZNUM" NOT NULL ENABLE);
  ALTER TABLE "FB"."SCENE" MODIFY ("STORYNUM" NOT NULL ENABLE);
  ALTER TABLE "FB"."SCENE" MODIFY ("SCENENUM" NOT NULL ENABLE);
